openapi: 3.0.0
info:
  title: Config
  version: v1.0
servers:
  - url: 'https://api.counterbalance.io'
    description: Production API
paths: {}
components:
  schemas: {}
  securitySchemes:
    Bearer Token:
      type: http
      scheme: bearer