openapi: 3.0.0
info:
  title: Config
  version: v1.0
  description: ''
  termsOfService: 'https://www.counterbalance.io/legal/api-terms'
  contact:
    name: Taylor Vick
    email: support@counterbalance.io
servers:
  - url: 'https://api.counterbalance.io'
    description: Production API
paths: {}
components:
  schemas: {}
  securitySchemes:
    Bearer Token:
      type: http
      scheme: bearer