openapi: 3.0.0
info:
  title: Sites
  version: v1.0
servers:
  - url: 'https://api.counterbalance.io'
    description: Production API
paths:
  /v1/site:
    get:
      summary: Get Site Listing
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                    description: The number of site objects returned
                  data:
                    type: array
                    minItems: 0
                    uniqueItems: true
                    description: An array of site objects
                    items:
                      type: object
                      $ref: '#/components/schemas/Site-Object-Generic'
                required:
                  - count
                  - data
      operationId: get-v1-site
      security:
        - Bearer Token: []
      description: Get a listing of sites
    post:
      summary: Create New Site
      operationId: post-v1-site
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Site-Object-Complete'
      description: Create a new site
      security:
        - Bearer Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 120
                  description: The name of the new site
                type:
                  type: string
                  enum:
                    - physical
                    - campus
                    - virtual
                  default: physical
                  description: The type of site to create
                code:
                  type: string
                  maxLength: 32
                  description: A unique code to identify the site
                description:
                  type: string
                  maxLength: 300
                  description: A description of the site
              required:
                - name
                - type
          application/xml:
            schema:
              type: object
              properties: {}
  '/v1/site/{siteId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: siteId
        in: path
        required: true
        description: The site's UUID
    get:
      summary: Get Site
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Site-Object-Complete'
      operationId: get-v1-site-siteId
      description: Get a site object by ID
      security:
        - Bearer Token: []
    patch:
      summary: Update Site
      operationId: patch-v1-site-siteId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Site-Object-Complete'
        '404':
          description: Site Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '../models/Error-Response.v1.yaml'
      description: |-
        Update a site by ID

        Use the `Update Address` endpoint to update the site's address
      security:
        - Bearer Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 120
                  description: The name of the site
                code:
                  type: string
                  description: The site's unique ID code
                  maxLength: 32
                description:
                  type: string
                  description: The description of the site
                  maxLength: 300
components:
  schemas:
    Site-Object-Complete:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
        code:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        type:
          type: string
          minLength: 1
        address:
          type: object
          $ref: '#/components/schemas/Address-Object'
        contacts: {}
      required:
        - id
        - code
        - name
        - description
        - type
        - address
    Site-Object-Generic:
      description: A generic site object used in site listings
      type: object
      title: Generic Site Object
      properties:
        id:
          type: string
          format: uuid
          description: The site's UUID
        type:
          type: string
          enum:
            - physical
            - campus
            - virtual
          description: The type of site
        code:
          type: string
          description: ''
          maxLength: 32
        name:
          type: string
          maxLength: 120
        description:
          type: string
          maxLength: 300
        address:
          type:
            - string
            - 'null'
          format: uuid
          description: An associated address object attached to this site
      required:
        - id
        - type
        - code
        - name
    Address-Object:
      description: ''
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The address object UUID
        lines:
          type: array
          minItems: 1
          maxItems: 2
          description: An array of address lines
          items:
            type: string
        locality:
          type: string
        city:
          type: string
          minLength: 1
        county:
          type: string
          minLength: 1
        state:
          type: string
          minLength: 1
        postcode:
          type: number
        country:
          type: string
        formatted:
          type: string
          minLength: 1
        geolocation:
          type: object
          required:
            - latitude
            - longitude
          properties:
            latitude:
              type: number
            longitude:
              type: number
        timezone:
          type: string
          minLength: 1
        offset:
          type: number
        designations:
          type: object
          required:
            - primary_mailing
            - primary_billing
          properties:
            primary_mailing:
              type: boolean
            primary_billing:
              type: boolean
      required:
        - id
        - lines
        - locality
        - city
        - county
        - state
        - postcode
        - country
        - formatted
        - geolocation
        - timezone
        - offset
        - designations
      title: Address Object
  securitySchemes:
    Bearer Token:
      type: http
      scheme: bearer
