openapi: 3.0.0
info:
  title: User
  version: 1.1.1
servers:
  - url: 'https://api.counterbalance.io'
    description: Core API
paths:
  /v1/user:
    get:
      summary: Get User Listing
      tags: []
      responses: {}
      operationId: get-v1-user
  '/v1/user/{userId}':
    parameters:
      - schema:
          type: string
          format: uuid
          example: 49b9c723-b995-11ea-8c37-00155debc00d
          minLength: 36
          maxLength: 36
        name: userId
        in: path
        required: true
        description: The UUID of the user to retrieve
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-v1-user-userId
      parameters: []
      description: Retrieve a user account by ID
components:
  schemas:
    User-Account:
      title: User-Account
      type: object
      properties:
        id:
          type: string
      description: ''
  securitySchemes:
    Bearer Token:
      type: http
      scheme: bearer
security:
  - Bearer Token: []
